const types = {
  SET_POSTS: "POSTS/SET_POSTS",
  SET_POST: "POSTS/SET_POST",
  SET_LOADING: "POSTS/SET_LOADING",
  SET_ERROR: "POSTS/SET_ERROR",
  SET_POST_LOADING: "POSTS/SET_POST_LOADING",
  SET_POST_ERROR: "POSTS/SET_POST_ERROR",
  ADD_COMMENT: "POSTS/ADD_COMMENT",
};

export default types;
